// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show  FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDy0uEMVOz7QrmgbjqYfrGh5B6WvITjUVc",
    authDomain: "maternal-app-v3.firebaseapp.com",
    projectId: "maternal-app-v3",
    storageBucket: "maternal-app-v3.firebasestorage.app",
    messagingSenderId: "27693036481",
    appId: "1:27693036481:web:c4e4492ad5936bf35db540");
  

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyDy0uEMVOz7QrmgbjqYfrGh5B6WvITjUVc",
    authDomain: "maternal-app-v3.firebaseapp.com",
    projectId: "maternal-app-v3",
    storageBucket: "maternal-app-v3.firebasestorage.app",
    messagingSenderId: "27693036481",
    appId: "1:27693036481:web:c4e4492ad5936bf35db540");

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyDy0uEMVOz7QrmgbjqYfrGh5B6WvITjUVc",
    authDomain: "maternal-app-v3.firebaseapp.com",
    projectId: "maternal-app-v3",
    storageBucket: "maternal-app-v3.firebasestorage.app",
    messagingSenderId: "27693036481",
    appId: "1:27693036481:web:c4e4492ad5936bf35db540");

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyDy0uEMVOz7QrmgbjqYfrGh5B6WvITjUVc",
    authDomain: "maternal-app-v3.firebaseapp.com",
    projectId: "maternal-app-v3",
    storageBucket: "maternal-app-v3.firebasestorage.app",
    messagingSenderId: "27693036481",
    appId: "1:27693036481:web:c4e4492ad5936bf35db540");

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyDy0uEMVOz7QrmgbjqYfrGh5B6WvITjUVc",
    authDomain: "maternal-app-v3.firebaseapp.com",
    projectId: "maternal-app-v3",
    storageBucket: "maternal-app-v3.firebasestorage.app",
    messagingSenderId: "27693036481",
    appId: "1:27693036481:web:c4e4492ad5936bf35db540");

}