import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'dart:async'; // Import for Future
import 'dart:convert'; // Import for JSON encoding/decoding
import 'package:http/http.dart' as http; // Import for making API calls
import 'package:intl/intl.dart'; // Import for date formatting
import 'package:flutter_dotenv/flutter_dotenv.dart';
// This file is auto-generated by `flutterfire configure`.
import 'firebase_options.dart';
import 'package:lucide_flutter/lucide_flutter.dart';
import 'package:flutter_markdown/flutter_markdown.dart'; // Import for Markdown

// --- Globals ---
const String appId = 'default-maternal-app';

// SAFE: Load the key from the environment

// --- Main Entry Point ---
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  // Load the .env file
  await dotenv.load(fileName: ".env");

  // *** THIS IS THE FIX ***
  // We check if Firebase has ALREADY been initialized.
  // This prevents the "[core/duplicate-app]" crash on macOS and iOS.
  if (Firebase.apps.isEmpty) {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  }
  runApp(const MyApp());
} //

// --- 1. Root App Widget ---
class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Maternal Health Hub',
      theme: ThemeData(
        primarySwatch: Colors.pink,
        colorScheme: ColorScheme.fromSwatch(primarySwatch: Colors.pink).copyWith(
          secondary: Colors.blueAccent,
        ),
        fontFamily: 'Inter',
        scaffoldBackgroundColor: const Color(0xFFF9FAFB),
        appBarTheme: const AppBarTheme(
          backgroundColor: Colors.white,
          elevation: 1,
          foregroundColor: Colors.black,
          titleTextStyle: TextStyle(
            color: Colors.black,
            fontSize: 20,
            fontWeight: FontWeight.bold,
          ),
        ),
        inputDecorationTheme: InputDecorationTheme(
          border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(12.0),
            borderSide: const BorderSide(color: Colors.grey),
          ),
          focusedBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(12.0),
            borderSide: const BorderSide(color: Colors.pink, width: 2.0),
          ),
        ),
        elevatedButtonTheme: ElevatedButtonThemeData(
          style: ElevatedButton.styleFrom(
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12.0),
            ),
            padding: const EdgeInsets.symmetric(vertical: 16.0),
          ),
        ),
        textButtonTheme: TextButtonThemeData(
          style: TextButton.styleFrom(
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12.0),
            ),
          ),
        ),
        bottomSheetTheme: const BottomSheetThemeData(
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
          ),
        ),
        cardTheme: CardThemeData(
          elevation: 2,
          margin: const EdgeInsets.symmetric(vertical: 8.0),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(12.0),
          ),
        ),
      ),
      debugShowCheckedModeBanner: false,
      home: const AuthWrapper(),
    );
  }
}

// --- 2. Auth Wrapper ---
class AuthWrapper extends StatelessWidget {
  const AuthWrapper({super.key});

  @override
  Widget build(BuildContext context) {
    // This builder automatically listens for login/logout events
    return StreamBuilder<User?>(
      stream: FirebaseAuth.instance.authStateChanges(),
      builder: (context, snapshot) {

        // 1. If still connecting, show loading screen
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const LoadingScreen(message: 'Connecting...');
        }

        // 2. If there's an error
        if (snapshot.hasError) {
          return ErrorScreen(message: 'Authentication error: ${snapshot.error}');
        }

        // 3. If we have data, check if user is null or not
        if (snapshot.hasData) {
          // User is logged IN
          return ProfileCheckWrapper(user: snapshot.data!);
        } else {
          // User is logged OUT
          return const AuthScreen();
        }
      },
    );
  }
}

// --- 3. Profile Check Wrapper ---
class ProfileCheckWrapper extends StatefulWidget {
  final User user;
  const ProfileCheckWrapper({super.key, required this.user});

  @override
  State<ProfileCheckWrapper> createState() => _ProfileCheckWrapperState();
}

class _ProfileCheckWrapperState extends State<ProfileCheckWrapper> {
  late final Future<DocumentSnapshot> _profileCheck;

  @override
  void initState() {
    super.initState();
    _profileCheck = FirebaseFirestore.instance
        .collection('artifacts')
        .doc(appId)
        .collection('users')
        .doc(widget.user.uid)
        .get();
  }

  @override
  Widget build(BuildContext context) {
    return FutureBuilder<DocumentSnapshot>(
      future: _profileCheck,
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const LoadingScreen(message: 'Loading profile...');
        }

        if (snapshot.hasError) {
          print('--- PROFILE CHECK FAILED ---');
          print(snapshot.error);
          print('-----------------------------');
          return ErrorScreen(
              message:
                  'Could not load profile. This is likely a database rules issue.\n\nError: ${snapshot.error}');
        }

        if (snapshot.data != null && snapshot.data!.exists) {
          final userData = snapshot.data!.data() as Map<String, dynamic>;
          return HomeScreen(user: widget.user, userData: userData);
        } else {
          return OnboardingScreen(user: widget.user);
        }
      },
    );
  }
}

// --- 4. Main App Home Screen (with Bottom Nav) ---
class HomeScreen extends StatefulWidget {
  final User user;
  final Map<String, dynamic> userData;

  const HomeScreen({super.key, required this.user, required this.userData});

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  int _selectedIndex = 0;
  late final List<Widget> _pages;

  @override
  void initState() {
    super.initState();
    _pages = [
      HomePageContent(
          user: widget.user,
          userData: widget.userData,
          onNavigate: _onItemTapped // Pass the navigation function
          ),
      MedicineScreen(user: widget.user),
      AppointmentsScreen(user: widget.user),
      NutritionScreen(userData: widget.userData, user: widget.user),
    ];
  }

  // This function is passed to HomePageContent
  void _onItemTapped(int index) {
    setState(() {
      _selectedIndex = index;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: IndexedStack(
        index: _selectedIndex,
        children: _pages,
      ),
      bottomNavigationBar: BottomNavigationBar(
        type: BottomNavigationBarType.fixed,
        currentIndex: _selectedIndex,
        onTap: _onItemTapped,
        selectedItemColor: Colors.pink,
        unselectedItemColor: Colors.grey[600],
        items: const [
          BottomNavigationBarItem(
            icon: Icon(LucideIcons.house),
            label: 'Home',
          ),
          BottomNavigationBarItem(
            icon: Icon(LucideIcons.pill),
            label: 'Meds',
          ),
          BottomNavigationBarItem(
            icon: Icon(LucideIcons.calendar),
            label: 'Appts',
          ),
          BottomNavigationBarItem(
            icon: Icon(LucideIcons.apple),
            label: 'Nutrition',
          ),
        ],
      ),
    );
  }
}

// --- 5. Screen Widgets ---

class LoadingScreen extends StatelessWidget {
  final String message;
  const LoadingScreen({super.key, this.message = 'Loading...'});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const CircularProgressIndicator(),
            const SizedBox(height: 20),
            Text(message, style: const TextStyle(color: Colors.grey)),
          ],
        ),
      ),
    );
  }
}

class ErrorScreen extends StatelessWidget {
  final String message;
  const ErrorScreen({super.key, this.message = 'An error occurred.'});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Padding(
          padding: const EdgeInsets.all(16.0),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              const Icon(LucideIcons.triangleAlert, color: Colors.red, size: 48),
              const SizedBox(height: 20),
              Text(
                message,
                style: const TextStyle(color: Colors.red),
                textAlign: TextAlign.center,
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class AuthScreen extends StatefulWidget {
  const AuthScreen({super.key});

  @override
  State<AuthScreen> createState() => _AuthScreenState();
}

class _AuthScreenState extends State<AuthScreen> {
  bool _isLogin = true;
  bool _isLoading = false;
  String _errorMessage = '';
  final _formKey = GlobalKey<FormState>();

  final _emailController = TextEditingController();
  final _passwordController = TextEditingController();

  @override
  void dispose() {
    _emailController.dispose();
    _passwordController.dispose();
    super.dispose();
  }

  Future<void> _handleSubmit() async {
    if (!_formKey.currentState!.validate()) {
      return;
    }

    setState(() {
      _isLoading = true;
      _errorMessage = '';
    });

    try {
      if (_isLogin) {
        await FirebaseAuth.instance.signInWithEmailAndPassword(
          email: _emailController.text.trim(),
          password: _passwordController.text.trim(),
        );
      } else {
        await FirebaseAuth.instance.createUserWithEmailAndPassword(
          email: _emailController.text.trim(),
          password: _passwordController.text.trim(),
        );
      }
    } on FirebaseAuthException catch (e) {
      print('--- AUTH FAILED ---');
      print(e);
      print('-------------------');
      setState(() {
        _errorMessage = e.message ?? 'An unknown authentication error occurred.';
      });
    } catch (e) {
      print('--- UNKNOWN AUTH/SIGNUP FAILED ---');
      print(e);
      print('------------------------------------');
      setState(() {
        _errorMessage =
            'An unexpected error occurred. Please try again.\n${e.toString()}';
      });
    } finally {
      if (mounted) {
        setState(() {
          _isLoading = false;
        });
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Center(
          child: SingleChildScrollView(
            child: Padding(
              padding: const EdgeInsets.all(24.0),
              child: Form(
                key: _formKey,
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  crossAxisAlignment: CrossAxisAlignment.stretch,
                  children: [
                    Row(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        Icon(LucideIcons.heartPulse,
                            color: Colors.pink[400], size: 48),
                        const SizedBox(width: 12),
                        Icon(LucideIcons.baby,
                            color: Colors.blue[400], size: 48),
                      ],
                    ),
                    const SizedBox(height: 24),
                    Text(
                      _isLogin ? 'Welcome Back' : 'Create Account',
                      textAlign: TextAlign.center,
                      style: Theme.of(context)
                          .textTheme
                          .headlineMedium
                          ?.copyWith(fontWeight: FontWeight.bold),
                    ),
                    const SizedBox(height: 8),
                    Text(
                      'Your partner in maternal health.',
                      textAlign: TextAlign.center,
                      style: Theme.of(context).textTheme.titleMedium,
                    ),
                    const SizedBox(height: 40),
                    TextFormField(
                      controller: _emailController,
                      decoration: const InputDecoration(
                        labelText: 'Email',
                        prefixIcon: Icon(LucideIcons.mail),
                      ),
                      keyboardType: TextInputType.emailAddress,
                      validator: (value) {
                        if (value == null ||
                            value.trim().isEmpty ||
                            !value.contains('@')) {
                          return 'Please enter a valid email.';
                        }
                        return null;
                      },
                    ),
                    const SizedBox(height: 16),
                    TextFormField(
                      controller: _passwordController,
                      decoration: const InputDecoration(
                        labelText: 'Password',
                        prefixIcon: Icon(LucideIcons.lock),
                      ),
                      obscureText: true,
                      validator: (value) {
                        if (value == null || value.trim().length < 6) {
                          return 'Password must be at least 6 characters.';
                        }
                        return null;
                      },
                    ),
                    const SizedBox(height: 24),
                    if (_errorMessage.isNotEmpty)
                      Padding(
                        padding: const EdgeInsets.only(bottom: 16.0),
                        child: Text(
                          _errorMessage,
                          style: const TextStyle(color: Colors.red),
                          textAlign: TextAlign.center,
                        ),
                      ),
                    ElevatedButton(
                      onPressed: _isLoading ? null : _handleSubmit,
                      child: _isLoading
                          ? const SizedBox(
                              height: 24,
                              width: 24,
                              child: CircularProgressIndicator(
                                strokeWidth: 2,
                                color: Colors.white,
                              ),
                            )
                          : Text(_isLogin ? 'Login' : 'Sign Up'),
                    ),
                    const SizedBox(height: 16),
                    TextButton(
                      onPressed: () {
                        setState(() {
                          _isLogin = !_isLogin;
                          _errorMessage = '';
                        });
                      },
                      child: Text(
                        _isLogin
                            ? 'Don\'t have an account? Sign Up'
                            : 'Already have an account? Login',
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}

class OnboardingScreen extends StatefulWidget {
  final User user;
  const OnboardingScreen({super.key, required this.user});

  @override
  State<OnboardingScreen> createState() => _OnboardingScreenState();
}

class _OnboardingScreenState extends State<OnboardingScreen> {
  final _formKey = GlobalKey<FormState>();
  bool _isLoading = false;
  String _errorMessage = '';

  final _nameController = TextEditingController();
  final _dueDateController = TextEditingController();
  final _historyController = TextEditingController();
  final _conditionsController = TextEditingController();
  final _allergiesController = TextEditingController();

  @override
  void dispose() {
    _nameController.dispose();
    _dueDateController.dispose();
    _historyController.dispose();
    _conditionsController.dispose();
    _allergiesController.dispose();
    super.dispose();
  }

  Future<void> _selectDate(BuildContext context) async {
    final DateTime? picked = await showDatePicker(
      context: context,
      initialDate: DateTime.now(),
      firstDate: DateTime.now().subtract(const Duration(days: 300)),
      lastDate: DateTime.now().add(const Duration(days: 300)),
    );
    if (picked != null) {
      setState(() {
        _dueDateController.text =
            "${picked.year}-${picked.month.toString().padLeft(2, '0')}-${picked.day.toString().padLeft(2, '0')}";
      });
    }
  }

  Future<void> _handleSaveProfile() async {
    if (!_formKey.currentState!.validate()) {
      return;
    }

    setState(() {
      _isLoading = true;
      _errorMessage = '';
    });

    final profileData = {
      'name': _nameController.text.trim(),
      'dueDate': _dueDateController.text.trim(),
      'medicalHistory': _historyController.text.trim(),
      'currentConditions': _conditionsController.text.trim(),
      'allergies': _allergiesController.text.trim(),
      'createdAt': FieldValue.serverTimestamp(),
    };

    try {
      final profileRef = FirebaseFirestore.instance
          .collection('artifacts')
          .doc(appId)
          .collection('users')
          .doc(widget.user.uid);

      await profileRef.set(profileData);

      if (mounted) {
        // This is a key fix: We use pushAndRemoveUntil to clear the nav stack
        // so the user can't go "back" to the onboarding screen.
        Navigator.of(context).pushAndRemoveUntil(
          MaterialPageRoute(builder: (context) => const AuthWrapper()),
          (Route<dynamic> route) => false,
        );
      }
    } catch (e) {
      print('--- PROFILE SAVE FAILED ---');
      print(e);
      print('---------------------------');
      if (mounted) {
        setState(() {
          _errorMessage =
              'Failed to save profile. Please try again.\n${e.toString()}';
          _isLoading = false;
        });
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Welcome!'),
      ),
      body: Form(
        key: _formKey,
        child: ListView(
          padding: const EdgeInsets.all(16.0),
          children: [
            Text(
              "Let's set up your profile.",
              style: Theme.of(context)
                  .textTheme
                  .headlineSmall
                  ?.copyWith(fontWeight: FontWeight.bold),
            ),
            const SizedBox(height: 8),
            const Text(
              "This information will help us personalize your experience.",
              style: TextStyle(color: Colors.grey),
            ),
            const SizedBox(height: 24),
            TextFormField(
              controller: _nameController,
              decoration: const InputDecoration(
                labelText: 'Full Name',
                prefixIcon: Icon(LucideIcons.user),
              ),
              validator: (value) {
                if (value == null || value.trim().isEmpty) {
                  return 'Please enter your name.';
                }
                return null;
              },
            ),
            const SizedBox(height: 16),
            TextFormField(
              controller: _dueDateController,
              decoration: const InputDecoration(
                labelText: 'Estimated Due Date',
                prefixIcon: Icon(LucideIcons.calendar),
              ),
              readOnly: true,
              onTap: () => _selectDate(context),
            ),
            const SizedBox(height: 16),
            TextFormField(
              controller: _historyController,
              decoration: const InputDecoration(
                labelText: 'Brief Medical History',
                hintText: 'e.g., previous pregnancies, surgeries',
                alignLabelWithHint: true,
              ),
              maxLines: 3,
            ),
            const SizedBox(height: 16),
            TextFormField(
              controller: _conditionsController,
              decoration: const InputDecoration(
                labelText: 'Current Medical Conditions',
                hintText: 'e.g., gestational diabetes',
                alignLabelWithHint: true,
              ),
              maxLines: 3,
            ),
            const SizedBox(height: 16),
            TextFormField(
              controller: _allergiesController,
              decoration: const InputDecoration(
                labelText: 'Allergies',
                hintText: 'medication, food, etc.',
                alignLabelWithHint: true,
              ),
              maxLines: 2,
            ),
            const SizedBox(height: 24),
            if (_errorMessage.isNotEmpty)
              Padding(
                padding: const EdgeInsets.only(bottom: 16.0),
                child: Text(
                  _errorMessage,
                  style: const TextStyle(color: Colors.red),
                  textAlign: TextAlign.center,
                ),
              ),
            ElevatedButton(
              onPressed: _isLoading ? null : _handleSaveProfile,
              child: _isLoading
                  ? const SizedBox(
                      height: 24,
                      width: 24,
                      child: CircularProgressIndicator(
                        strokeWidth: 2,
                        color: Colors.white,
                      ),
                    )
                  : const Text('Save Profile'),
            ),
          ],
        ),
      ),
    );
  }
}

// --- 6. Page Content ---

// --- HomePage ---
class HomePageContent extends StatefulWidget {
  final User user;
  final Map<String, dynamic> userData;
  final Function(int) onNavigate; // Callback to change tabs

  const HomePageContent({
    super.key,
    required this.user,
    required this.userData,
    required this.onNavigate,
  });

  @override
  State<HomePageContent> createState() => _HomePageContentState();
}

class _HomePageContentState extends State<HomePageContent> {
  late final Stream<QuerySnapshot> _appointmentsStream;
  late final Stream<QuerySnapshot> _medicinesStream;

  @override
  void initState() {
    super.initState();

    // Stream for next upcoming appointment
    _appointmentsStream = FirebaseFirestore.instance
        .collection('artifacts')
        .doc(appId)
        .collection('users')
        .doc(widget.user.uid)
        .collection('appointments')
        .where('date', isGreaterThanOrEqualTo: Timestamp.now())
        .orderBy('date')
        .limit(1)
        .snapshots();

    // Stream for next pending medicine
    _medicinesStream = FirebaseFirestore.instance
        .collection('artifacts')
        .doc(appId)
        .collection('users')
        .doc(widget.user.uid)
        .collection('medicines')
        .where('isTaken', isEqualTo: false)
        .orderBy('createdAt')
        .limit(1)
        .snapshots();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Maternal Health Hub'),
        actions: [
          IconButton(
            icon: const Icon(LucideIcons.logOut),
            onPressed: () {
              FirebaseAuth.instance.signOut();
            },
          )
        ],
      ),
      body: ListView(
        padding: const EdgeInsets.all(16.0),
        children: [
          Text(
            'Welcome, ${widget.userData['name'] ?? 'User'}!',
            style: Theme.of(context).textTheme.headlineMedium?.copyWith(
                  fontWeight: FontWeight.bold,
                ),
          ),
          const SizedBox(height: 8),
          Text(
            "Here's your summary. Stay healthy!",
            style: Theme.of(context).textTheme.titleMedium?.copyWith(
                  color: Colors.grey[700],
                ),
          ),
          const SizedBox(height: 24),
          _buildNextAppointmentCard(),
          _buildNextMedicineCard(),
          _buildNutritionCard(context),
        ],
      ),
    );
  }

  // --- Dashboard Card Widgets ---

  // A generic card builder
  Widget _buildDashboardCard({
    required BuildContext context,
    required IconData icon,
    required Color iconColor,
    required String title,
    required Widget content,
    required VoidCallback onTap,
  }) {
    return Card(
      child: InkWell(
        onTap: onTap,
        borderRadius: BorderRadius.circular(12.0),
        child: Padding(
          padding: const EdgeInsets.all(16.0),
          child: Row(
            children: [
              Icon(icon, color: iconColor, size: 32),
              const SizedBox(width: 16),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      title,
                      style: Theme.of(context).textTheme.titleLarge?.copyWith(
                            fontWeight: FontWeight.bold,
                          ),
                    ),
                    const SizedBox(height: 4),
                    content,
                  ],
                ),
              ),
              const Icon(LucideIcons.chevronRight, color: Colors.grey),
            ],
          ),
        ),
      ),
    );
  }

  // Card for next appointment
  Widget _buildNextAppointmentCard() {
    return StreamBuilder<QuerySnapshot>(
      stream: _appointmentsStream,
      builder: (context, snapshot) {
        Widget content;
        if (snapshot.connectionState == ConnectionState.waiting) {
          content = const Text('Loading...', style: TextStyle(color: Colors.grey));
        } else if (snapshot.hasError) {
          print("--- APPOINTMENT STREAM ERROR ---");
          print(snapshot.error);
          print("--------------------------------");
          content = const Text('Error loading data', style: TextStyle(color: Colors.red));
        } else if (!snapshot.hasData || snapshot.data!.docs.isEmpty) {
          content =
              const Text('No upcoming appointments', style: TextStyle(color: Colors.grey));
        } else {
          final doc = snapshot.data!.docs.first;
          final data = doc.data() as Map<String, dynamic>;
          final DateTime date = (data['date'] as Timestamp).toDate();
          content = Text(
            '${data['title']} on ${DateFormat.yMd().format(date)}',
            style: const TextStyle(fontWeight: FontWeight.bold),
          );
        }

        return _buildDashboardCard(
          context: context,
          icon: LucideIcons.calendar,
          iconColor: Colors.blueAccent,
          title: 'Next Appointment',
          content: content,
          onTap: () => widget.onNavigate(2), // Navigate to Appts tab
        );
      },
    );
  }

  // Card for next medicine
  Widget _buildNextMedicineCard() {
    return StreamBuilder<QuerySnapshot>(
      stream: _medicinesStream,
      builder: (context, snapshot) {
        Widget content;
        if (snapshot.connectionState == ConnectionState.waiting) {
          content = const Text('Loading...', style: TextStyle(color: Colors.grey));
        } else if (snapshot.hasError) {
          print("--- MEDICINE STREAM ERROR ---");
          print(snapshot.error);
          print("-------------------------------");
          content = const Text('Error loading data', style: TextStyle(color: Colors.red));
        } else if (!snapshot.hasData || snapshot.data!.docs.isEmpty) {
          content =
              const Text('All medicines taken!', style: TextStyle(color: Colors.grey));
        } else {
          final doc = snapshot.data!.docs.first;
          final data = doc.data() as Map<String, dynamic>;
          content = Text(
            '${data['name']} - ${data['time']}',
            style: const TextStyle(fontWeight: FontWeight.bold),
          );
        }

        return _buildDashboardCard(
          context: context,
          icon: LucideIcons.pill,
          iconColor: Colors.pink,
          title: 'Next Medicine',
          content: content,
          onTap: () => widget.onNavigate(1), // Navigate to Meds tab
        );
      },
    );
  }

  // Card for nutrition tips
  Widget _buildNutritionCard(BuildContext context) {
    return _buildDashboardCard(
      context: context,
      icon: LucideIcons.apple,
      iconColor: Colors.amber[700]!,
      title: 'Nutrition Tips',
      content: const Text('Get AI-powered tips for a healthy pregnancy.'),
      onTap: () => widget.onNavigate(3), // Navigate to Nutrition tab
    );
  }
}

// --- MedicineScreen ---
class MedicineScreen extends StatefulWidget {
  final User user;
  const MedicineScreen({super.key, required this.user});

  @override
  State<MedicineScreen> createState() => _MedicineScreenState();
}

class _MedicineScreenState extends State<MedicineScreen> {
  late final CollectionReference _medicineRef;

  @override
  void initState() {
    super.initState();
    _medicineRef = FirebaseFirestore.instance
        .collection('artifacts')
        .doc(appId)
        .collection('users')
        .doc(widget.user.uid)
        .collection('medicines');
  }

  Future<void> _addMedicine(
      String name, String dosage, String time, BuildContext modalContext) async {
    if (name.isEmpty) return;
    try {
      await _medicineRef.add({
        'name': name,
        'dosage': dosage,
        'time': time,
        'isTaken': false,
        'createdAt': FieldValue.serverTimestamp(),
      });
      Navigator.of(modalContext).pop();
    } catch (e) {
      print("Error adding medicine: $e");
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Failed to add medicine: ${e.toString()}')),
        );
      }
    }
  }

  Future<void> _toggleIsTaken(DocumentSnapshot doc) async {
    try {
      await doc.reference.update({'isTaken': !doc['isTaken']});
    } catch (e) {
      print("Error updating medicine: $e");
    }
  }
  // *** NEW ***
  // Function to delete a medicine
  Future<void> _deleteMedicine(DocumentSnapshot doc) async {
    try {
      await doc.reference.delete();
      if (mounted) {
         ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('${doc['name']} deleted.'),
            backgroundColor: Colors.red,
          ),
        );
      }
    } catch (e) {
      print("Error deleting medicine: $e");
    }
  }

  void _showAddMedicineSheet() {
    final nameController = TextEditingController();
    final dosageController = TextEditingController();
    
    final timeController = TextEditingController();
    TimeOfDay? selectedTime = TimeOfDay.now();

    showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      builder: (modalContext) {
        return StatefulBuilder(
          builder: (BuildContext context, StateSetter setModalState) {
            // *** FIX ***
            // Wrap the Column in a SingleChildScrollView
            // and use the padding for viewInsets
            return Padding(
              padding: EdgeInsets.only(
                bottom: MediaQuery.of(context).viewInsets.bottom,
                top: 20,
                left: 20,
                right: 20,
              ),
              child: SingleChildScrollView(
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  crossAxisAlignment: CrossAxisAlignment.stretch,
                  children: [
                    Text(
                      'Add New Medicine',
                      style: Theme.of(context).textTheme.headlineSmall,
                      textAlign: TextAlign.center,
                    ),
                    const SizedBox(height: 24),
                    TextField(
                      controller: nameController,
                      decoration: const InputDecoration(labelText: 'Medicine Name'),
                    ),
                    const SizedBox(height: 16),
                    TextField(
                      controller: dosageController,
                      decoration: const InputDecoration(labelText: 'Dosage (e.g., 1 pill)'),
                    ),
                    const SizedBox(height: 16),
                    TextFormField(
                      controller: timeController,
                      readOnly: true,
                      decoration: const InputDecoration(
                        labelText: 'Time',
                        prefixIcon: Icon(LucideIcons.clock),
                      ),
                      onTap: () async {
                        final TimeOfDay? picked = await showTimePicker(
                          context: context,
                          initialTime: selectedTime ?? TimeOfDay.now(),
                        );
                        if (picked != null) {
                          setModalState(() {
                            selectedTime = picked;
                            // Use context from StatefulBuilder for formatting
                            timeController.text = picked.format(context); 
                          });
                        }
                      },
                    ),
                    const SizedBox(height: 24),
                    ElevatedButton(
                      onPressed: () {
                        if(timeController.text.isEmpty) {
                          ScaffoldMessenger.of(modalContext).showSnackBar(
                            const SnackBar(content: Text('Please select a time.'), backgroundColor: Colors.red,),
                          );
                          return;
                        }
                        _addMedicine(
                          nameController.text,
                          dosageController.text,
                          timeController.text, // Pass the formatted time
                          modalContext,
                        );
                      },
                      child: const Text('Save Medicine'),
                    ),
                    const SizedBox(height: 20),
                  ],
                ),
              ),
            );
          },
        );
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Maternal Health Hub'),
      ),
      body: StreamBuilder<QuerySnapshot>(
        stream: _medicineRef.orderBy('createdAt').snapshots(),
        builder: (context, snapshot) {
          if (snapshot.hasError) {
            return const Center(child: Text('Error loading medicines.'));
          }
          if (snapshot.connectionState == ConnectionState.waiting) {
            return const Center(child: CircularProgressIndicator());
          }
          if (snapshot.data!.docs.isEmpty) {
            return const Center(
              child: Text(
                'No medicines added yet.\nTap the + button to add one.',
                textAlign: TextAlign.center,
                style: TextStyle(color: Colors.grey),
              ),
            );
          }

          return ListView(
            padding: const EdgeInsets.all(8.0),
            children: snapshot.data!.docs.map((doc) {
              final data = doc.data() as Map<String, dynamic>;
              final bool isTaken = data['isTaken'] ?? false;
              
              // *** MODIFIED ***
              // Wrap list tile in Dismissible
              return Dismissible(
                key: Key(doc.id), 
                onDismissed: (direction) {
                  _deleteMedicine(doc);
                },
                background: Container(
                  color: Colors.red,
                  alignment: Alignment.centerRight,
                  padding: const EdgeInsets.symmetric(horizontal: 20.0),
                  child: const Icon(LucideIcons.trash2, color: Colors.white),
                ),
                child: Card(
                  child: ListTile(
                    contentPadding: const EdgeInsets.symmetric(vertical: 10, horizontal: 16),
                    title: Text(
                      data['name'],
                      style: TextStyle(
                        fontWeight: FontWeight.bold,
                        decoration: isTaken ? TextDecoration.lineThrough : null,
                      ),
                    ),
                    subtitle: Text(
                      '${data['dosage']} - ${data['time']}',
                      style: TextStyle(
                        decoration: isTaken ? TextDecoration.lineThrough : null,
                      ),
                    ),
                    trailing: Checkbox(
                      value: isTaken,
                      onChanged: (bool? value) {
                        _toggleIsTaken(doc);
                      },
                      activeColor: Colors.pink,
                    ),
                    onTap: () {
                      _toggleIsTaken(doc);
                    },
                  ),
                ),
              );
            }).toList(),
          );
        },
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _showAddMedicineSheet,
        tooltip: 'Add Medicine',
        child: const Icon(LucideIcons.plus),
      ),
    );
  }
}

// --- AppointmentsScreen ---
class AppointmentsScreen extends StatefulWidget {
  final User user;
  const AppointmentsScreen({super.key, required this.user});

  @override
  State<AppointmentsScreen> createState() => _AppointmentsScreenState();
}

class _AppointmentsScreenState extends State<AppointmentsScreen> {
  late final CollectionReference _appointmentRef;

  @override
  void initState() {
    super.initState();
    _appointmentRef = FirebaseFirestore.instance
        .collection('artifacts')
        .doc(appId)
        .collection('users')
        .doc(widget.user.uid)
        .collection('appointments');
  }

  Future<void> _addAppointment(
      String title, String type, DateTime date, BuildContext modalContext) async {
    if (title.isEmpty) return;
    try {
      await _appointmentRef.add({
        'title': title,
        'type': type,
        'date': Timestamp.fromDate(date),
        'createdAt': FieldValue.serverTimestamp(),
      });
      Navigator.of(modalContext).pop();
    } catch (e) {
      print("Error adding appointment: $e");
      if(mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Failed to add appointment: ${e.toString()}')),
        );
      }
    }
  }

  // *** NEW ***
  // Function to delete an appointment
  Future<void> _deleteAppointment(DocumentSnapshot doc) async {
    try {
      await doc.reference.delete();
      if (mounted) {
         ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('${doc['title']} deleted.'),
            backgroundColor: Colors.red,
          ),
        );
      }
    } catch (e) {
      print("Error deleting appointment: $e");
    }
  }

  void _showAddAppointmentSheet() {
    final titleController = TextEditingController();
    final typeController = TextEditingController();
    DateTime? selectedDate = DateTime.now();

    showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      builder: (modalContext) {
        return StatefulBuilder(
          builder: (BuildContext context, StateSetter setModalState) {
            // *** FIX ***
            // Wrap the Column in a SingleChildScrollView
            // and use the padding for viewInsets
            return Padding(
              padding: EdgeInsets.only(
                bottom: MediaQuery.of(context).viewInsets.bottom,
                top: 20,
                left: 20,
                right: 20,
              ),
              child: SingleChildScrollView(
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  crossAxisAlignment: CrossAxisAlignment.stretch,
                  children: [
                    Text(
                      'Add New Appointment',
                      style: Theme.of(context).textTheme.headlineSmall,
                      textAlign: TextAlign.center,
                    ),
                    const SizedBox(height: 24),
                    TextField(
                      controller: titleController,
                      decoration: const InputDecoration(labelText: 'Appointment Title'),
                    ),
                    const SizedBox(height: 16),
                    TextField(
                      controller: typeController,
                      decoration: const InputDecoration(
                          labelText: 'Type (e.g., Checkup, Vaccine)'),
                    ),
                    const SizedBox(height: 16),
                    TextFormField(
                      readOnly: true,
                      decoration: InputDecoration(
                        labelText:
                            'Date: ${DateFormat.yMd().format(selectedDate!)}',
                        prefixIcon: const Icon(LucideIcons.calendar),
                      ),
                      onTap: () async {
                        final DateTime? picked = await showDatePicker(
                          context: context,
                          initialDate: selectedDate!,
                          firstDate: DateTime.now(),
                          lastDate: DateTime.now().add(const Duration(days: 365)),
                        );
                        if (picked != null && picked != selectedDate) {
                          setModalState(() {
                            selectedDate = picked;
                          });
                        }
                      },
                    ),
                    const SizedBox(height: 24),
                    ElevatedButton(
                      onPressed: () {
                        _addAppointment(
                          titleController.text,
                          typeController.text,
                          selectedDate!,
                          modalContext,
                        );
                      },
                      child: const Text('Save Appointment'),
                    ),
                    const SizedBox(height: 20),
                  ],
                ),
              ),
            );
          },
        );
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Maternal Health Hub'),
      ),
      body: StreamBuilder<QuerySnapshot>(
        stream: _appointmentRef.orderBy('date').snapshots(),
        builder: (context, snapshot) {
          if (snapshot.hasError) {
            return const Center(child: Text('Error loading appointments.'));
          }
          if (snapshot.connectionState == ConnectionState.waiting) {
            return const Center(child: CircularProgressIndicator());
          }
          if (snapshot.data!.docs.isEmpty) {
            return const Center(
              child: Text(
                'No appointments scheduled.\nTap the + button to add one.',
                textAlign: TextAlign.center,
                style: TextStyle(color: Colors.grey),
              ),
            );
          }

          return ListView(
            padding: const EdgeInsets.all(8.0),
            children: snapshot.data!.docs.map((doc) {
              final data = doc.data() as Map<String, dynamic>;
              final DateTime date = (data['date'] as Timestamp).toDate();
              
              // *** MODIFIED ***
              // Wrap list tile in Dismissible
              return Dismissible(
                key: Key(doc.id),
                onDismissed: (direction) {
                  _deleteAppointment(doc);
                },
                background: Container(
                  color: Colors.red,
                  alignment: Alignment.centerRight,
                  padding: const EdgeInsets.symmetric(horizontal: 20.0),
                  child: const Icon(LucideIcons.trash2, color: Colors.white),
                ),
                child: Card(
                  child: ListTile(
                    contentPadding: const EdgeInsets.symmetric(vertical: 10, horizontal: 16),
                    leading: CircleAvatar(
                      backgroundColor: Colors.blue[100],
                      child: Text(
                        DateFormat.d().format(date),
                        style: const TextStyle(
                          fontWeight: FontWeight.bold,
                          color: Colors.blueAccent,
                        ),
                      ),
                    ),
                    title: Text(
                      data['title'],
                      style: const TextStyle(fontWeight: FontWeight.bold),
                    ),
                    subtitle: Text(
                        '${data['type']} - ${DateFormat.yMMMd().format(date)}'),
                    trailing: const Icon(LucideIcons.chevronRight),
                  ),
                ),
              );
            }).toList(),
          );
        },
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _showAddAppointmentSheet,
        backgroundColor: Colors.blueAccent,
        tooltip: 'Add Appointment',
        child: const Icon(LucideIcons.plus),
      ),
    );
  }
}

// --- NutritionScreen ---
class NutritionScreen extends StatefulWidget {
  final Map<String, dynamic> userData;
  final User user;
  const NutritionScreen({super.key, required this.userData, required this.user});

  @override
  State<NutritionScreen> createState() => _NutritionScreenState();
}

class _NutritionScreenState extends State<NutritionScreen> {
  bool _isLoading = false;
  String? _aiResponse;
  String? _errorMessage;

  Future<void> _getNutritionTips() async {
    final String geminiApiKey = dotenv.env['GEMINI_API_KEY'] ?? 'YOUR_GEMINI_API_KEY_HERE';
    setState(() {
      _isLoading = true;
      _errorMessage = null;
      _aiResponse = null;
    });

    if (geminiApiKey == "YOUR_GEMINI_API_KEY_HERE" || geminiApiKey.isEmpty) {
       setState(() {
        _errorMessage = "API Key is not set. Please create a .env file with your Gemini API Key.";
        _isLoading = false;
      });
      return;
    }

    // Create a prompt from the user's profile data
    final prompt = """
    You are a helpful and caring nutritional assistant for maternal health.
    A user has provided the following health profile. Please provide 5-7 actionable,
    safe, and personalized nutritional tips based on this data.
    Address the user directly (e.g., "Based on your...").
    
    USER PROFILE:
    - Name: ${widget.userData['name']}
    - Estimated Due Date: ${widget.userData['dueDate']}
    - Medical History: ${widget.userData['medicalHistory']}
    - Current Conditions: ${widget.userData['currentConditions']}
    - Allergies: ${widget.userData['allergies']}
    
    Please provide your tips as a bulleted list.
    """;

    final url = Uri.parse(
        'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-preview-09-2025:generateContent?key=$geminiApiKey');

    try {
      final response = await http.post(
        url,
        headers: {'Content-Type': 'application/json'},
        body: jsonEncode({
          'contents': [
            {
              'parts': [
                {'text': prompt}
              ]
            }
          ]
        }),
      );

      if (response.statusCode == 200) {
        final data = jsonDecode(response.body);
        final text =
            data['candidates'][0]['content']['parts'][0]['text'] as String;
        setState(() {
          _aiResponse = text;
        });
      } else {
        final errorBody = jsonDecode(response.body);
        setState(() {
          _errorMessage =
              'Error from AI: ${errorBody['error']['message'] ?? 'Unknown error'}';
        });
      }
    } catch (e) {
      setState(() {
        _errorMessage = 'Failed to connect to AI service: ${e.toString()}';
      });
    } finally {
      setState(() {
        _isLoading = false;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Maternal Health Hub'),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16.0),
        child: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Text(
                'Personalized Nutrition',
                style: Theme.of(context).textTheme.headlineSmall,
              ),
              const SizedBox(height: 8),
              const Text(
                'Get AI-powered tips based on your profile.',
                textAlign: TextAlign.center,
                style: TextStyle(color: Colors.grey),
              ),
              const SizedBox(height: 32),
              ElevatedButton(
                onPressed: _isLoading ? null : _getNutritionTips,
                style: ElevatedButton.styleFrom(
                  backgroundColor: Colors.amber[700],
                ),
                child: const Text('Get My Tips'),
              ),
              const SizedBox(height: 32),
              if (_isLoading)
                const CircularProgressIndicator(),
              if (_errorMessage != null)
                Text(
                  _errorMessage!,
                  style: const TextStyle(color: Colors.red),
                  textAlign: TextAlign.center,
                ),
              if (_aiResponse != null)
                // *** MODIFIED ***
                // Replaced SelectableText with MarkdownBody
                Container(
                  padding: const EdgeInsets.all(16.0),
                  decoration: BoxDecoration(
                    color: Colors.white,
                    borderRadius: BorderRadius.circular(12.0),
                    border: Border.all(color: Colors.grey[200]!),
                  ),
                  child: MarkdownBody( // Use MarkdownBody
                    data: _aiResponse!,
                    selectable: true,
                    styleSheet: MarkdownStyleSheet.fromTheme(Theme.of(context)).copyWith(
                      p: const TextStyle(fontSize: 16, height: 1.5),
                    ),
                  ),
                ),
            ],
          ),
        ),
      ),
    );
  }
}